security:
    encoders:
        Application\Sonata\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_POLCODE_HR: [ROLE_USER, ROLE_POLCODE, ROLE_SONATA_ADMIN]
        ROLE_POLCODE:
            - ROLE_POLCODE_RECRUITMENT_ADMIN_EMPLOYEE_LIST
            - ROLE_POLCODE_RECRUITMENT_ADMIN_EMPLOYEE_VIEW
            - ROLE_POLCODE_RECRUITMENT_ADMIN_EMPLOYEE_CREATE
            - ROLE_POLCODE_RECRUITMENT_ADMIN_EMPLOYEE_EDIT
            - ROLE_POLCODE_RECRUITMENT_ADMIN_EMPLOYEE_DELETE
            - ROLE_POLCODE_RECRUITMENT_ADMIN_EMPLOYEE_EXPORT
            - ROLE_POLCODE_RECRUITMENT_ADMIN_AM_LIST
            - ROLE_POLCODE_RECRUITMENT_ADMIN_AM_VIEW
            - ROLE_POLCODE_RECRUITMENT_ADMIN_AM_CREATE
            - ROLE_POLCODE_RECRUITMENT_ADMIN_AM_EDIT
            - ROLE_POLCODE_RECRUITMENT_ADMIN_AM_DELETE
            - ROLE_POLCODE_RECRUITMENT_ADMIN_AM_EXPORT
            - ROLE_POLCODE_RECRUITMENT_ADMIN_PROJECT_LIST
            - ROLE_POLCODE_RECRUITMENT_ADMIN_PROJECT_VIEW
            - ROLE_POLCODE_RECRUITMENT_ADMIN_PROJECT_CREATE
            - ROLE_POLCODE_RECRUITMENT_ADMIN_PROJECT_EDIT
            - ROLE_POLCODE_RECRUITMENT_ADMIN_PROJECT_DELETE
            - ROLE_POLCODE_RECRUITMENT_ADMIN_PROJECT_EXPORT
            
    access_decision_manager:
        strategy: unanimous

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|admin/_(wdt|profiler)|api/_(wdt|profiler))/
            security: false

        # This firewall is used to handle the admin login area
        # This part is handled by the Sonata User Bundle
        admin:
            pattern:            /(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
                invalidate_session: false
            anonymous:    true

    access_control:

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # It also secures the shop checkout process
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_USER] }
        - { path: ^/.*, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_USER] }
        
       